/*
 * Copyright (c) 2016. Codetector (Yaotian Feng)
 */

export const USER = 'USER'
export const USER_FAILURE = 'USER_FAILURE'
export const USER_ERROR = 'USER_ERROR'
export const USER_PERMISSIONS_CHANGE = 'USER_PERMISSIONS_CHANGE'
export const USER_EMAIL_CHANGE = 'USER_EMAIL_CHANGE'
export const USER_NAME_CHANGE = 'USER_NAME_CHANGE'
export const USER_PHONE_CHANGE = 'USER_PHONE_CHANGE'
export const USER_ID_CHANGE = 'USER_ID_CHANGE'
export const USER_LOGIN_HISTORY_CHANGE = 'USER_LOGIN_HISTORY_CHANGE'
export const USER_MFA_STATUS_CHANGE = 'USER_MFA_STATUS_CHANGE'

export const SHOW_LOADING_SPINNER = 'SHOW_LOADING_SPINNER'
export const HIDE_LOADING_SPINNER = 'HIDE_LOADING_SPINNER'
